- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Create directory for downloads
    file:
      path: downloads
      state: directory
      
  - name: Download required fronend packages
    uri: 
      url: "{{ item }}"
      dest: downloads
      creates: "{{ item.split('/')[-1] }}"
    with_items:
     - https://code.jquery.com/jquery-3.2.1.min.js
     - https://github.com/d3/d3/releases/download/v4.10.0/d3.zip
     - https://github.com/c3js/c3/archive/v0.4.15.zip
     - http://underscorejs.org/underscore-min.js
     - https://github.com/twbs/bootstrap/releases/download/v4.0.0-alpha.6/bootstrap-4.0.0-alpha.6-dist.zip